PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?compoundRes ?compoundResLabel ?id WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    SELECT ?compound ?id WHERE {
      ?compound wdt:P715 ?id .
    }
  }
}
