PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT DISTINCT ?compound ?id WHERE {
  ?compound wdt:P665 ?id .
  BIND (SUBSTR(?id,1,1) AS ?type)
  FILTER (?type != "H")
  FILTER (?type != "R")
}
