PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?compoundRes ?compoundResLabel ?id WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    SELECT ?compoundRes ?mesh WITH {
      { ?compoundRes p:P31/ps:P31 wd:Q11173 }
      UNION
      { ?compoundRes p:P31/ps:P31 wd:Q36496 }
      UNION
      { ?compoundRes p:P31/ps:P31 wd:Q79529 }
      UNION
      { ?compoundRes p:P279/ps:P279 wd:Q11173 }
      UNION
      { ?compoundRes p:P279/ps:P279 wd:Q79529 }
      ?compoundRes wdt:P486 ?mesh .
    }
  }
}
