PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?compound ?id WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    SELECT DISTINCT ?compound ?id WHERE {
      ?compound wdt:P662 ?id .
    }
  }
}
